//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from piVC.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IpiVCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class piVCBaseListener : IpiVCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] piVCParser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] piVCParser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecl([NotNull] piVCParser.DeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecl([NotNull] piVCParser.DeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.declInsideClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclInsideClass([NotNull] piVCParser.DeclInsideClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.declInsideClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclInsideClass([NotNull] piVCParser.DeclInsideClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] piVCParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] piVCParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.fnDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnDecl([NotNull] piVCParser.FnDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.fnDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnDecl([NotNull] piVCParser.FnDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDecl([NotNull] piVCParser.ClassDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDecl([NotNull] piVCParser.ClassDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.beforeFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBeforeFunc([NotNull] piVCParser.BeforeFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.beforeFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBeforeFunc([NotNull] piVCParser.BeforeFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.beforeBranch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBeforeBranch([NotNull] piVCParser.BeforeBranchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.beforeBranch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBeforeBranch([NotNull] piVCParser.BeforeBranchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] piVCParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] piVCParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.formalsOrEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalsOrEmpty([NotNull] piVCParser.FormalsOrEmptyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.formalsOrEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalsOrEmpty([NotNull] piVCParser.FormalsOrEmptyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.formals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormals([NotNull] piVCParser.FormalsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.formals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormals([NotNull] piVCParser.FormalsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] piVCParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] piVCParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.varOutSideOfFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOutSideOfFunc([NotNull] piVCParser.VarOutSideOfFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.varOutSideOfFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOutSideOfFunc([NotNull] piVCParser.VarOutSideOfFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.paramVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamVar([NotNull] piVCParser.ParamVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.paramVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamVar([NotNull] piVCParser.ParamVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.stmtBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtBlock([NotNull] piVCParser.StmtBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.stmtBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtBlock([NotNull] piVCParser.StmtBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.varDeclOutsideOfFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclOutsideOfFunc([NotNull] piVCParser.VarDeclOutsideOfFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.varDeclOutsideOfFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclOutsideOfFunc([NotNull] piVCParser.VarDeclOutsideOfFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDecl([NotNull] piVCParser.VarDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.varDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDecl([NotNull] piVCParser.VarDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] piVCParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] piVCParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.varDeclAndAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclAndAssign([NotNull] piVCParser.VarDeclAndAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.varDeclAndAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclAndAssign([NotNull] piVCParser.VarDeclAndAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] piVCParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] piVCParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] piVCParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] piVCParser.WhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] piVCParser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] piVCParser.ForStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.termination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermination([NotNull] piVCParser.TerminationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.termination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermination([NotNull] piVCParser.TerminationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.terminationArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminationArgs([NotNull] piVCParser.TerminationArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.terminationArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminationArgs([NotNull] piVCParser.TerminationArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] piVCParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] piVCParser.ReturnStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.breakStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStmt([NotNull] piVCParser.BreakStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.breakStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStmt([NotNull] piVCParser.BreakStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.assertStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssertStmt([NotNull] piVCParser.AssertStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.assertStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssertStmt([NotNull] piVCParser.AssertStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.commaSeperatedListOfUniversalVarDecls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommaSeperatedListOfUniversalVarDecls([NotNull] piVCParser.CommaSeperatedListOfUniversalVarDeclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.commaSeperatedListOfUniversalVarDecls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommaSeperatedListOfUniversalVarDecls([NotNull] piVCParser.CommaSeperatedListOfUniversalVarDeclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.commaSeperatedListOfExistentialVarDecls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommaSeperatedListOfExistentialVarDecls([NotNull] piVCParser.CommaSeperatedListOfExistentialVarDeclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.commaSeperatedListOfExistentialVarDecls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommaSeperatedListOfExistentialVarDecls([NotNull] piVCParser.CommaSeperatedListOfExistentialVarDeclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.lValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLValue([NotNull] piVCParser.LValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.lValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLValue([NotNull] piVCParser.LValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] piVCParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] piVCParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.callInterior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallInterior([NotNull] piVCParser.CallInteriorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.callInterior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallInterior([NotNull] piVCParser.CallInteriorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] piVCParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] piVCParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] piVCParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] piVCParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.annotationExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationExpr([NotNull] piVCParser.AnnotationExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.annotationExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationExpr([NotNull] piVCParser.AnnotationExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.annotationWithLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationWithLabel([NotNull] piVCParser.AnnotationWithLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.annotationWithLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationWithLabel([NotNull] piVCParser.AnnotationWithLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.annotationPre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationPre([NotNull] piVCParser.AnnotationPreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.annotationPre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationPre([NotNull] piVCParser.AnnotationPreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="piVCParser.annotationPost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationPost([NotNull] piVCParser.AnnotationPostContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="piVCParser.annotationPost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationPost([NotNull] piVCParser.AnnotationPostContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
